version: 2

project_name: blinkcli

before:
  hooks:
    - go mod tidy

builds:
  - id: blinkcli
    main: ./cmd/blinkcli
    binary: blinkcli
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz

checksum:
  name_template: checksums.txt

homebrew_casks:
  - name: blinkcli
    directory: Casks
    homepage: https://github.com/maheshrijal/blinkcli
    description: Unofficial Blinkit order tracker CLI
    license: MIT
    binaries:
      - blinkcli
    repository:
      owner: maheshrijal
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: Mahesh Rijal
      email: 62394512+maheshrijal@users.noreply.github.com
